import { LevelConfig } from './index'

const levelConfig: LevelConfig = {
  M: 31,
  N: 28,
  map: [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'X............XX............X',
    'X.XXXX.XXXXX.XX.XXXXX.XXXX.X',
    'XPXXXX.XXXXX.XX.XXXXX.XXXXPX',
    'X.XXXX.XXXXX.XX.XXXXX.XXXX.X',
    'X..........................X',
    'X.XXXX.XX.XXXXXXXX.XX.XXXX.X',
    'X.XXXX.XX.XXXXXXXX.XX.XXXX.X',
    'X......XX....XX....XX......X',
    'XXXXXX.XXXXX XX XXXXX.XXXXXX',
    'XXXXXX.XXXXX XX XXXXX.XXXXXX',
    'XXXXXX.XX          XX.XXXXXX',
    'XXXXXX.XX XXXDDXXX XX.XXXXXX',
    'XXXXXX.XX X      X XX.XXXXXX',
    '      .   X      X   .      ',
    'XXXXXX.XX X      X XX.XXXXXX',
    'XXXXXX.XX XXXXXXXX XX.XXXXXX',
    'XXXXXX.XX          XX.XXXXXX',
    'XXXXXX.XX XXXXXXXX XX.XXXXXX',
    'XXXXXX.XX XXXXXXXX XX.XXXXXX',
    'X............XX............X',
    'X.XXXX.XXXXX.XX.XXXXX.XXXX.X',
    'X.XXXX.XXXXX.XX.XXXXX.XXXX.X',
    'XP..XX................XX..PX',
    'XXX.XX.XX.XXXXXXXX.XX.XX.XXX',
    'XXX.XX.XX.XXXXXXXX.XX.XX.XXX',
    'X......XX....XX....XX......X',
    'X.XXXXXXXXXX.XX XXXXXXXXXX.X',
    'X.XXXXXXXXXX.XX XXXXXXXXXX.X',
    'X..........................X',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  ],
  wallColor: '#0e2275',
}

export default levelConfig
